//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyticData
    {
        public AnalyticData()
        {
            this.BarChart = new HashSet<BarChart>();
            this.LineChart = new HashSet<LineChart>();
            this.MoveTable = new HashSet<MoveTable>();
            this.NonStackedBarChart = new HashSet<NonStackedBarChart>();
            this.StackedBarchart = new HashSet<StackedBarchart>();
            this.TableModal = new HashSet<TableModal>();
        }
    
        public int Id { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> ModalViewCellId { get; set; }
    
        public virtual ModalViewCell ModalViewCell { get; set; }
        public virtual TypeAnalyticData TypeAnalyticData { get; set; }
        public virtual ICollection<BarChart> BarChart { get; set; }
        public virtual ICollection<LineChart> LineChart { get; set; }
        public virtual ICollection<MoveTable> MoveTable { get; set; }
        public virtual ICollection<NonStackedBarChart> NonStackedBarChart { get; set; }
        public virtual ICollection<StackedBarchart> StackedBarchart { get; set; }
        public virtual ICollection<TableModal> TableModal { get; set; }
    }
}
