//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyzeLog
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string Message { get; set; }
        public System.DateTime Date { get; set; }
        public int TypeId { get; set; }
        public string FullDescription { get; set; }
    
        public virtual AnalyzeMessageType AnalyzeMessageType { get; set; }
        public virtual Documents Documents { get; set; }
    }
}
