//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CellStyleTemplates
    {
        public CellStyleTemplates()
        {
            this.Cell = new HashSet<Cell>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FontWeight { get; set; }
        public string BackgroundColor { get; set; }
        public string FontColor { get; set; }
        public string CellType { get; set; }
        public string Align { get; set; }
        public string DFM { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public string FontFamily { get; set; }
        public string FontStyle { get; set; }
        public string DecorLine { get; set; }
        public int Indent { get; set; }
        public int FontSize { get; set; }
        public string CellDataFormat { get; set; }
        public Nullable<bool> Calculation { get; set; }
    
        public virtual ICollection<Cell> Cell { get; set; }
        public virtual CellStyleTemplates CellStyleTemplates1 { get; set; }
        public virtual CellStyleTemplates CellStyleTemplates2 { get; set; }
    }
}
