//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CellModalStyle
    {
        public int Id { get; set; }
        public Nullable<int> FontSize { get; set; }
        public string FontFamily { get; set; }
        public string FontStyle { get; set; }
        public string Align { get; set; }
        public string LinkColor { get; set; }
        public string FontColor { get; set; }
        public string BackgroundColor { get; set; }
        public int CellModalId { get; set; }
    
        public virtual CellModal CellModal { get; set; }
    }
}
