//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cell
    {
        public Cell()
        {
            this.RelationCells = new HashSet<RelationCells>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public string Value { get; set; }
        public int RowId { get; set; }
        public Nullable<int> ModalViewId { get; set; }
        public Nullable<int> CellStyleId { get; set; }
        public Nullable<int> ReportCellType { get; set; }
        public Nullable<int> ReportDocumentType { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> SourceDocumentRowNumber { get; set; }
        public string SourceDocumentHash { get; set; }
        public string Editable { get; set; }
        public Nullable<bool> Calculation { get; set; }
    
        public virtual ReportCellTypeCatalog ReportCellTypeCatalog { get; set; }
        public virtual ReportDocumentTypeCatalog ReportDocumentTypeCatalog { get; set; }
        public virtual CellStyleTemplates CellStyleTemplates { get; set; }
        public virtual ICollection<RelationCells> RelationCells { get; set; }
    }
}
