//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CellStyles
    {
        public int Id { get; set; }
        public string FontWeight { get; set; }
        public Nullable<int> FontSize { get; set; }
        public string BackgroundColor { get; set; }
        public string FontColor { get; set; }
        public string CellType { get; set; }
        public string CellDataFormat { get; set; }
        public string Align { get; set; }
        public string DFM { get; set; }
        public int CellId { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public string FontFamily { get; set; }
        public Nullable<bool> Calc { get; set; }
        public string DecorLine { get; set; }
        public string FontStyle { get; set; }
        public Nullable<int> Indent { get; set; }
    }
}
