//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentControlVersion
    {
        public int Id { get; set; }
        public int DocId { get; set; }
        public int Version { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int UserId { get; set; }
        public bool State { get; set; }
    
        public virtual Documents Documents { get; set; }
        public virtual Users Users { get; set; }
    }
}
