//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineChartElement
    {
        public LineChartElement()
        {
            this.LineChartPoint = new HashSet<LineChartPoint>();
        }
    
        public int Id { get; set; }
        public int LineChartId { get; set; }
        public string Description { get; set; }
    
        public virtual LineChart LineChart { get; set; }
        public virtual ICollection<LineChartPoint> LineChartPoint { get; set; }
    }
}
