//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModalViewCell
    {
        public ModalViewCell()
        {
            this.AnalyticData = new HashSet<AnalyticData>();
        }
    
        public int Id { get; set; }
        public int RowId { get; set; }
        public int Number { get; set; }
    
        public virtual ICollection<AnalyticData> AnalyticData { get; set; }
        public virtual ModalViewRow ModalViewRow { get; set; }
    }
}
