//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoveCategories
    {
        public MoveCategories()
        {
            this.MoveTableRow = new HashSet<MoveTableRow>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual MoveCategories MoveCategories1 { get; set; }
        public virtual MoveCategories MoveCategories2 { get; set; }
        public virtual ICollection<MoveTableRow> MoveTableRow { get; set; }
    }
}
