//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoveTableRow
    {
        public MoveTableRow()
        {
            this.MoveTableCell = new HashSet<MoveTableCell>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public int MoveTableId { get; set; }
        public Nullable<int> MoveCategoryId { get; set; }
    
        public virtual MoveCategories MoveCategories { get; set; }
        public virtual MoveTable MoveTable { get; set; }
        public virtual ICollection<MoveTableCell> MoveTableCell { get; set; }
    }
}
