//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoveTableCell
    {
        public int Id { get; set; }
        public int Number { get; set; }
        public int MoveTableRowId { get; set; }
        public string Category { get; set; }
        public string Value { get; set; }
    
        public virtual MoveTableRow MoveTableRow { get; set; }
    }
}
