//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public int Id { get; set; }
        public System.DateTime TimeAddToQueue { get; set; }
        public int ClientId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> OperationType { get; set; }
        public Nullable<int> OperationState { get; set; }
        public string OperationCommand { get; set; }
    
        public virtual OperationState OperationState1 { get; set; }
        public virtual OperationType OperationType1 { get; set; }
    }
}
