//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public Projects()
        {
            this.Documents = new HashSet<Documents>();
            this.SourceDocuments = new HashSet<SourceDocuments>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int ClientId { get; set; }
        public int State { get; set; }
        public string ProjectName { get; set; }
        public bool SourceDocumentsIsLoaded { get; set; }
        public string Period { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<Documents> Documents { get; set; }
        public virtual ProjectStates ProjectStates { get; set; }
        public virtual ICollection<SourceDocuments> SourceDocuments { get; set; }
    }
}
