//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDocumentTypeCatalog
    {
        public ReportDocumentTypeCatalog()
        {
            this.Cell = new HashSet<Cell>();
            this.LineChartPoint = new HashSet<LineChartPoint>();
            this.NonStackedBarChartElement = new HashSet<NonStackedBarChartElement>();
            this.PieChartElement = new HashSet<PieChartElement>();
            this.SourceDocumentCell = new HashSet<SourceDocumentCell>();
            this.StackedBarchartElement = new HashSet<StackedBarchartElement>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Cell> Cell { get; set; }
        public virtual ICollection<LineChartPoint> LineChartPoint { get; set; }
        public virtual ICollection<NonStackedBarChartElement> NonStackedBarChartElement { get; set; }
        public virtual ICollection<PieChartElement> PieChartElement { get; set; }
        public virtual ICollection<SourceDocumentCell> SourceDocumentCell { get; set; }
        public virtual ICollection<StackedBarchartElement> StackedBarchartElement { get; set; }
    }
}
