//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RowModal
    {
        public RowModal()
        {
            this.CellModal = new HashSet<CellModal>();
        }
    
        public int Id { get; set; }
        public int ModalBodyId { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual BodyModal BodyModal { get; set; }
        public virtual ICollection<CellModal> CellModal { get; set; }
    }
}
