//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceDocumentCell
    {
        public int Id { get; set; }
        public int SourceDocumentRowId { get; set; }
        public int Number { get; set; }
        public string Value { get; set; }
        public string Name { get; set; }
        public string ValueType { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public Nullable<int> AnalyticDataType { get; set; }
    
        public virtual ReportCellTypeCatalog ReportCellTypeCatalog { get; set; }
        public virtual ReportDocumentTypeCatalog ReportDocumentTypeCatalog { get; set; }
        public virtual SourceDocumentRow SourceDocumentRow { get; set; }
    }
}
