//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceDocumentSheet
    {
        public SourceDocumentSheet()
        {
            this.SourceDocumentRow = new HashSet<SourceDocumentRow>();
        }
    
        public int Id { get; set; }
        public int SourceDocumentId { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SourceDocumentRow> SourceDocumentRow { get; set; }
        public virtual SourceDocuments SourceDocuments { get; set; }
    }
}
