//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceDocumentStates
    {
        public SourceDocumentStates()
        {
            this.SourceDocuments = new HashSet<SourceDocuments>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SourceDocuments> SourceDocuments { get; set; }
    }
}
