//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StackedBarchartColumn
    {
        public StackedBarchartColumn()
        {
            this.StackedBarchartElement = new HashSet<StackedBarchartElement>();
        }
    
        public int Id { get; set; }
        public string PositionX { get; set; }
        public string Description { get; set; }
        public int StackedBarChartId { get; set; }
    
        public virtual StackedBarchart StackedBarchart { get; set; }
        public virtual ICollection<StackedBarchartElement> StackedBarchartElement { get; set; }
    }
}
