//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.DocumentControlVersion = new HashSet<DocumentControlVersion>();
            this.SourceDocuments = new HashSet<SourceDocuments>();
            this.UserLogins = new HashSet<UserLogins>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string LastName { get; set; }
        public string Department { get; set; }
        public int Roles { get; set; }
        public string Rights { get; set; }
        public int ClientId { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<DocumentControlVersion> DocumentControlVersion { get; set; }
        public virtual ICollection<SourceDocuments> SourceDocuments { get; set; }
        public virtual ICollection<UserLogins> UserLogins { get; set; }
        public virtual UserRoles UserRoles { get; set; }
    }
}
